import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Linking,ScrollView,Share,Text,TextInput,View} from 'react-native';
import {careApi,CareCase,CareMutation,concernLabels,Intake} from '../api/careApi';
import {ActionCard,Back,Button,Choice,ui} from '../components/CareUI';
import {CalendarField} from '../components/CalendarField';
import {COLORS} from '../theme/colors';

type Screen='home'|'concern'|'intake'|'case'|'brief'|'plan';
const localDate=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const requestKey=()=>`care-${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
const caseLabel=(careCase:CareCase)=>careCase.intake.concern==='other'&&careCase.intake.concern_detail?.trim()?careCase.intake.concern_detail:concernLabels[careCase.intake.concern];
export const CareScreen:React.FC<{initialMode?:'home'|'concern';initialCaseID?:string}>=({initialMode='home',initialCaseID})=>{
 const[screen,setScreen]=useState<Screen>(initialCaseID?'case':initialMode);const[cases,setCases]=useState<CareCase[]>([]);const[current,setCurrent]=useState<CareCase|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[key,setKey]=useState(requestKey);
 const[concern,setConcern]=useState('');const[concernDetail,setConcernDetail]=useState('');const[onset,setOnset]=useState('');const[severity,setSeverity]=useState<number|null>(null);const[impact,setImpact]=useState('');const[pregnancy,setPregnancy]=useState('');const[urgent,setUrgent]=useState<boolean|null>(null);const[details,setDetails]=useState('');const[history,setHistory]=useState(true);const[selectedFacts,setSelectedFacts]=useState<string[]>([]);const[taskTitle,setTaskTitle]=useState('');const[due,setDue]=useState(localDate);const[showArchived,setShowArchived]=useState(false);
 const changeScreen=(s:Screen)=>{setScreen(s);setError('')};
 const load=async()=>{setError('');try{setCases(await careApi.list());if(initialCaseID)setCurrent(await careApi.get(initialCaseID))}catch{setError('Could not load your care. Try again.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{setKey(requestKey())},[concern,concernDetail,onset,severity,impact,pregnancy,urgent,details,history]);
 const open=async(id:string)=>{setBusy(true);setError('');try{setCurrent(await careApi.get(id));setScreen('case')}catch{setError('Could not open this case. Try again.')}finally{setBusy(false)}};
 const start=()=>{setKey(requestKey());setConcern('');setConcernDetail('');setOnset('');setSeverity(null);setImpact('');setPregnancy('');setUrgent(null);setDetails('');setCurrent(null);changeScreen('concern')};
 const submit=async()=>{
  if(!concern||!onset.trim()||severity===null||!impact||!pregnancy||urgent===null||(concern==='other'&&!concernDetail.trim())){setError('Complete the questions before continuing.');return}
  setBusy(true);setError('');try{const intake:Intake={concern,concern_detail:concern==='other'?concernDetail.trim():undefined,onset,severity,impact,pregnancy,urgent_symptoms:urgent,details,include_history:history};const c=await careApi.create(intake,key);setCurrent(c);setCases(old=>[c,...old.filter(v=>v.id!==c.id)]);setScreen('case')}catch(e:any){setError(e.response?.data?.error||'Could not save your concern. Try again.')}finally{setBusy(false)}
 };
 const mutate=async(m:Omit<CareMutation,'revision'>)=>{if(!current)return;setBusy(true);setError('');try{const c=await careApi.update(current.id,{...m,revision:current.revision});setCurrent(c);setCases(old=>old.map(v=>v.id===c.id?c:v));if(m.action==='add_task')setTaskTitle('')}catch(e:any){setError(e.response?.data?.error||'Could not save. Try again.');if(e.response?.status===409){try{setCurrent(await careApi.get(current.id))}catch{}}}finally{setBusy(false)}};
 const review=()=>{if(!current)return;setSelectedFacts(current.facts.map(f=>f.id));changeScreen('brief')};
 const organize=async()=>{if(!current)return;setBusy(true);setError('');try{setCurrent(await careApi.brief(current.id,current.revision))}catch{setError('Your saved summary is still available. Try again.')}finally{setBusy(false)}};
 const share=async()=>{if(!current)return;const facts=current.facts.filter(f=>selectedFacts.includes(f.id));const message=['Sadé · Health summary',`Recorded ${new Date(current.created_at).toLocaleDateString()}`,'Patient-reported information; not a diagnosis.',...facts.map(f=>`${f.label}${f.date?` (${f.date})`:''}: ${f.value}`),'Safety check: '+current.assessment.title,current.assessment.guidance].join('\n\n');try{await Share.share({message})}catch{setError('Sharing is unavailable. Select and copy the summary instead.')}};
 const urgentNotice=<View style={[ui.card,{backgroundColor:'#FFF0EC',borderColor:'#F0C9BC'}]}><Text style={ui.label}>Urgent warning signs</Text><Text style={ui.text}>For sudden severe pain, fainting or very heavy bleeding, seek urgent medical care. Do not wait for an appointment in Sadé.</Text></View>;
 return <ScrollView key={screen} style={ui.page} keyboardShouldPersistTaps="handled" contentContainerStyle={ui.content}>
  {screen!=='home'?<Back onPress={()=>changeScreen(screen==='intake'?'concern':screen==='brief'||screen==='plan'?'case':'home')}/>:null}
  {error&&screen!=='intake'?<View accessibilityRole="alert" style={ui.card}><Text style={ui.error}>{error}</Text>{screen==='home'||(!current&&initialCaseID)?<Button label="Retry" secondary onPress={load}/>:null}</View>:null}
  {screen==='home'?<><Text style={ui.title}>Your care</Text><ActionCard title="I Have a Concern" detail="Start a safety check" icon="shield-check-outline" tone="primary" onPress={start}/>{urgentNotice}<View style={ui.row}><Text style={[ui.heading,{flex:1}]}>My care cases</Text><Choice label="Archived" selected={showArchived} onPress={()=>setShowArchived(!showArchived)}/></View>{loading?<ActivityIndicator color={COLORS.primary}/>:cases.filter(c=>showArchived?c.status==='archived':c.status==='open').length?cases.filter(c=>showArchived?c.status==='archived':c.status==='open').map(c=><ActionCard key={c.id} title={caseLabel(c)} detail={`${new Date(c.created_at).toLocaleDateString()} · ${c.tasks.filter(t=>t.status==='pending').length} next steps`} icon="clipboard-text-outline" onPress={()=>open(c.id)}/>):!error?<View style={ui.card}><Text style={ui.text}>{showArchived?'No archived cases.':'No ongoing care. Start with a concern to prepare your health summary.'}</Text></View>:null}</>:null}
  {screen==='concern'?<><Text style={ui.eyebrow}>Step 1 of 2</Text><Text style={ui.title}>What’s concerning you?</Text>{urgentNotice}<View style={{gap:10}}>{Object.entries(concernLabels).map(([id,label])=><Choice key={id} label={label} selected={concern===id} onPress={()=>setConcern(id)}/>)}</View>{concern==='other'?<><Text style={ui.label}>Describe your concern</Text><TextInput accessibilityLabel="Describe your concern" style={ui.input} value={concernDetail} onChangeText={setConcernDetail} maxLength={200} placeholder="Type your main concern"/></>:null}<Button label="Continue" disabled={!concern||(concern==='other'&&!concernDetail.trim())} onPress={()=>changeScreen('intake')}/></>:null}
  {screen==='intake'?<><Text style={ui.eyebrow}>Step 2 of 2</Text><Text style={ui.title}>{concern==='other'?concernDetail:concernLabels[concern]}</Text>
   <View style={ui.card}><Text style={ui.label}>Are you experiencing sudden severe pain, fainting or very heavy bleeding?</Text><View style={ui.wrap}><Choice label="Yes" selected={urgent===true} onPress={()=>setUrgent(true)}/><Choice label="No" selected={urgent===false} onPress={()=>setUrgent(false)}/></View>{urgent===true?urgentNotice:null}</View>
   <Text style={ui.label}>When did it start?</Text><TextInput accessibilityLabel="When did it start?" style={ui.input} value={onset} onChangeText={setOnset} maxLength={100} placeholder="For example, this morning or three cycles ago"/>
   <Text style={ui.label}>How severe is it now?</Text><View style={ui.wrap}>{Array.from({length:11},(_,i)=><Choice key={i} label={String(i)} selected={severity===i} onPress={()=>setSeverity(i)}/>)}</View><Text style={ui.small}>0 · None     10 · Worst imaginable</Text>
   <Text style={ui.label}>How is it affecting your day?</Text><View style={{gap:8}}>{['Usual activities unaffected','Activities are harder','Unable to do usual activities'].map(v=><Choice key={v} label={v} selected={impact===v} onPress={()=>setImpact(v)}/>)}</View>
   <Text style={ui.label}>Could you be pregnant?</Text><View style={ui.wrap}>{[['yes','Yes'],['no','No'],['unknown','Not sure']].map(([id,label])=><Choice key={id} label={label} selected={pregnancy===id} onPress={()=>setPregnancy(id)}/>)}</View>
   <Text style={ui.label}>Anything else? <Text style={ui.small}>Optional</Text></Text><TextInput accessibilityLabel="Additional concern details" style={[ui.input,{minHeight:100,textAlignVertical:'top'}]} multiline value={details} onChangeText={setDetails} maxLength={4000}/>
   <Choice label="Include my cycle, symptom and medication history" selected={history} onPress={()=>setHistory(!history)}/><Text style={ui.small}>Journal entries stay private.</Text>{error?<Text accessibilityRole="alert" style={ui.error}>{error}</Text>:null}<Button label="See my next step" onPress={submit} busy={busy}/>
  </>:null}
  {screen==='case'&&!current&&loading?<ActivityIndicator color={COLORS.primary}/>:null}
  {screen==='case'&&current?<><Text style={ui.eyebrow}>{caseLabel(current)}</Text><Text style={ui.title}>Your next step</Text><View style={[ui.card,current.assessment.urgency==='urgent'?{borderColor:COLORS.error}:{}]}><Text style={ui.heading}>{current.assessment.title}</Text><Text style={ui.text}>{current.assessment.guidance}</Text></View>
   {current.packages.length>0?<><Text style={ui.heading}>Recommended care</Text><Text style={ui.small}>Sample care options for testing.</Text>{current.packages.map(p=><View key={p.id} style={ui.card}>{p.sample?<Text style={ui.eyebrow}>Sample</Text>:null}<Text style={ui.heading}>{p.name}</Text><Text style={ui.text}>{p.description}</Text>{p.includes.map(v=><Text key={v} style={ui.text}>✓  {v}</Text>)}<Text style={ui.label}>{p.provider}</Text><Text style={ui.heading}>{new Intl.NumberFormat('en-NG',{style:'currency',currency:p.currency,maximumFractionDigits:0}).format(p.price_minor/100)}</Text>{current.status==='open'?<Button label={current.selected_package_id===p.id?(p.sample?'Sample selected':'Continue with provider'):(p.sample?'Choose sample package':'Choose this package')} disabled={p.sample&&current.selected_package_id===p.id} busy={busy} onPress={async()=>{if(current.selected_package_id!==p.id){await mutate({action:'select_package',package_id:p.id});return}if(p.sample)return;try{await Linking.openURL(p.booking_url)}catch{setError('Could not open the provider. Try again.')}}}/>:null}</View>)}<Text style={ui.small}>Sample selections do not create appointments or collect payment.</Text></>:null}
   <ActionCard title="Review health summary" detail="Choose what to share with your provider" icon="file-document-outline" onPress={review}/><ActionCard title="My follow-up plan" detail={`${current.tasks.filter(t=>t.status==='pending').length} next steps`} icon="clipboard-check-outline" tone="muted" onPress={()=>changeScreen('plan')}/>
   {current.status==='open'?<><Button label="Report a new or changed concern" secondary onPress={start}/>{current.tasks.every(t=>t.status==='completed')?<Button label="Archive case" secondary onPress={()=>mutate({action:'archive'})} busy={busy}/>:null}</>:<Button label="Reopen case" secondary onPress={()=>mutate({action:'reopen'})} busy={busy}/>}</>:null}
  {screen==='brief'&&current?<><Text style={ui.title}>Review your summary</Text><Text style={ui.small}>Patient-reported information · {new Date(current.created_at).toLocaleDateString()}</Text>{current.brief.sections.map((section,i)=><View key={i} style={{gap:10}}><Text style={ui.heading}>{section.heading}</Text>{section.fact_ids.map(id=>{const f=current.facts.find(v=>v.id===id);return f?<View key={id} style={ui.card}><View style={ui.row}><Text style={[ui.label,{flex:1}]}>{f.label}</Text><Choice label="Include" selected={selectedFacts.includes(id)} onPress={()=>setSelectedFacts(old=>old.includes(id)?old.filter(v=>v!==id):[...old,id])}/></View><Text selectable style={ui.text}>{f.value}</Text>{f.date?<Text style={ui.small}>{f.date}</Text>:null}</View>:null})}</View>)}<Text style={ui.small}>The safety-check result is always included. Share only with someone you trust.</Text><Button label="Share summary" onPress={share} disabled={selectedFacts.length===0}/>{current.brief.ai_available?<Button label="Prepare clinician brief" secondary busy={busy} onPress={organize}/>:null}</>:null}
  {screen==='plan'&&current?<><Text style={ui.title}>Your follow-up plan</Text><Button label="My symptoms have changed" secondary onPress={start}/>{current.tasks.length?current.tasks.map(t=><View key={t.id} style={ui.card}><Text style={ui.label}>{t.title}</Text><Text style={ui.small}>Due {t.due_date} · Added by you</Text>{current.status==='open'?<Button label={t.status==='completed'?'Mark incomplete':'Mark complete'} secondary busy={busy} onPress={()=>mutate({action:'update_task',task_id:t.id,status:t.status==='completed'?'pending':'completed'})}/>:<Text style={ui.small}>Completed</Text>}</View>):<Text style={ui.text}>Add the next steps agreed with your provider.</Text>}{current.status==='open'?<View style={ui.card}><Text style={ui.heading}>Add a next step</Text><TextInput accessibilityLabel="Next step" style={ui.input} placeholder="For example, attend a follow-up appointment" value={taskTitle} maxLength={200} onChangeText={setTaskTitle}/><CalendarField label="Due date" value={due} onChange={setDue}/><Button label="Add to my plan" disabled={!taskTitle.trim()} busy={busy} onPress={()=>mutate({action:'add_task',title:taskTitle,due_date:due})}/></View>:null}</>:null}
 </ScrollView>
};
