import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Image,Platform,ScrollView,Text,TextInput,View} from 'react-native';
import QRCode from 'qrcode';
import {Button,ui} from '../components/CareUI';
import {pharmacyHandoffApi,PublicPharmacyHandoff} from '../api/handoffApi';
import {COLORS} from '../theme/colors';

export const ExternalPharmacyHandoffScreen:React.FC<{token:string}>=({token})=>{
 const[handoff,setHandoff]=useState<PublicPharmacyHandoff|null>(null);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[qr,setQR]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{pharmacyHandoffApi.get(token).then(setHandoff).catch((e)=>setError(e.response?.data?.error||'This prescription is unavailable.'));if(Platform.OS==='web'&&typeof window!=='undefined')QRCode.toDataURL(window.location.href,{width:220,margin:1,color:{dark:'#681227',light:'#FFFFFF'}}).then(setQR).catch(()=>undefined)},[token]);
 const update=async(action:string)=>{if(action==='check_in'&&(!name.trim()||phone.trim().length<7)){setError('Enter the pharmacy name and phone number.');return}setBusy(true);setError('');try{setHandoff(await pharmacyHandoffApi.update(token,{action,provider_name:name,phone}))}catch(e:any){setError(e.response?.data?.error||'Could not update this prescription.')}finally{setBusy(false)}};
 const print=()=>{if(Platform.OS==='web'&&typeof window!=='undefined')window.print()};
 if(!handoff&&!error)return <View style={[ui.page,{alignItems:'center',justifyContent:'center'}]}><ActivityIndicator color={COLORS.primary}/></View>;
 return <ScrollView style={ui.page} contentContainerStyle={[ui.content,{maxWidth:660,alignSelf:'center',width:'100%'}]}><Text style={ui.eyebrow}>Sadé care handoff</Text><Text style={ui.title}>Prescription</Text>{error?<View style={ui.card}><Text style={ui.error}>{error}</Text></View>:null}{handoff?<><View style={ui.card}><Text style={ui.eyebrow}>Prescription {handoff.reference}</Text><Text style={ui.heading}>{handoff.medicine} · {handoff.dose}</Text><Text style={ui.text}>{handoff.frequency} for {handoff.duration_days} days</Text>{handoff.instructions?<Text style={ui.text}>{handoff.instructions}</Text>:null}<Text style={ui.small}>Patient: {handoff.patient_name} · Prescribed by {handoff.prescribed_by}</Text>{qr?<Image source={{uri:qr}} style={{width:180,height:180,alignSelf:'center',marginTop:12}}/>:null}<Button label="Print or save as PDF" secondary onPress={print}/></View>{handoff.status==='issued'?<View style={ui.card}><Text style={ui.heading}>Pharmacy check-in</Text><TextInput style={ui.input} placeholder="Pharmacy name" value={name} onChangeText={setName}/><TextInput style={ui.input} placeholder="Phone number" keyboardType="phone-pad" value={phone} onChangeText={setPhone}/><Button label="Confirm pharmacy" busy={busy} onPress={()=>update('check_in')}/></View>:null}{handoff.status==='checked_in'?<View style={ui.card}><Text style={ui.heading}>Confirm dispensing</Text><Text style={ui.text}>{handoff.provider_name} has checked in.</Text><Button label="Mark medication dispensed" busy={busy} onPress={()=>update('mark_dispensed')}/></View>:null}{handoff.status==='dispensed'?<View style={[ui.card,{backgroundColor:COLORS.emeraldLight}]}><Text style={ui.heading}>Medication dispensed</Text><Text style={ui.text}>The patient’s dosage tracker is ready.</Text></View>:null}</>:null}</ScrollView>;
};
